
name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Project Files
        run: ls -la

      - name: Show Backend Files
        run: ls -la backend

      - name: Show Client Files
        run: ls -la client

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      - name: Install Client Dependencies
        working-directory: client
        run: npm install

      - name: Build Backend
        working-directory: backend
        run: npm run build

      - name: Build Client
        working-directory: client
        run: npm run build
